

export enum RepositoryEnum{

    CLIENT="CLIENT_REPOSITORY",
    CLIENT_SALE="CLIENT_SALE_REPOSITORY",
    DEPARTMENT="DEPARTMENT_REPOSITORY",
    PRODUCT="PRODUCT_REPOSITORY",
    ROLE="ROLE_REPOSITORY",
    ROLE_DEPARTMENT="ROLE_DEPARTMENT_REPOSITORY",
    SALE_PRODUCT="SALE_PRODUCT_REPOSITORY",
    SALE="SALE_REPOSITORY",
    USER="USER_REPOSITORY"
}